name: Java Matrix CI

on:
  push:
    branches: [testing_java_matrix]
  pull_request:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          MATRIX=$(jq -c -n \
            --argjson temurin '["17.0.14+7"]' \
            --argjson zulu '["17.0.2+8","17.0.10+7"]' \
            --argjson corretto '["17"]' \
            --argjson liberica '["17.0.8+7"]' \
            '{include: (
              ([$temurin[] | {vendor:"temurin", version: .}])
              + ([$zulu[] | {vendor:"zulu", version: .}])
              + ([$corretto[] | {vendor:"corretto", version: .}])
              + ([$liberica[] | {vendor:"liberica", version: .}])
            )}')
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT
          echo "Generated matrix: $MATRIX"
        shell: bash
 
 
  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ matrix.version }} from ${{ matrix.vendor }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.vendor }}
          java-version: ${{ matrix.version }}

      - name: Verify Java version
        run: java -version

      - name: Run tests
        run: ./gradlew :core:analytics:compileDemoDebugJavaWithJavac -Dscan.tag."${{ matrix.vendor }}"  -Dscan.tag."${{ matrix.version }}" -Dscan.tag.uploading_apks
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_KEY }}
      - name: Archive Comparison Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: files-${{ matrix.vendor }}-${{ matrix.version }}
          path: |
            /home/runner/.gradle/caches/8.13/transforms/*
          if-no-files-found: error
